### ISSUE TITLE
Uvicorn Worker Does Not Handle Gunicorn pre_request and post_request Server Hooks

### ISSUE THREAD

**Issue by khaled5321** [Kludex/uvicorn-worker#23]
The pre_request and post_request server hooks are not currently handled in the Uvicorn worker.

This issue originates from a discussion in the Gunicorn repository: https://github.com/benoitc/gunicorn/issues/2723

**Comment by Kludex** [comment]
PR welcome.

**Comment by Kludex** [comment]
- Duplicated of https://github.com/Kludex/uvicorn-worker/issues/20
